---

   - name: ansible create multiple directory example
     file:
       path: "{{ item }}"
       state: directory
       owner: mysql
       group: mysql
     with_items:
       - '/apps'
       - '/apps/mysql'
       - '/apps/mysql/data'
       - '/apps/mysql/binlog'
       - '/apps/mysql/relaylog'
       - '/apps/mysql/backup'
       - '/apps/mysql/logs'
       - '/apps/mysql/tmp'

